stages:
  - build
  - inspect

build_image:
  stage: build
  script:
    - docker build -t tcn.re/inspectr/dashboard .
    - docker push tcn.re/inspectr/dashboard
  tags:
    - shell

inspect:
  stage: inspect
  script:
    - docker run -v $(pwd):/code -v /home/gitlab-runner/inspectr_connector_docker.json:/root/.inspectr_connector.json tcn.re/inspectr/inspectr || true
    - docker run -v $(pwd):/code tcn.re/inspectr/inspectr find /code -user root -exec rm -rf "{}" ';' || true
  tags:
    - shell
